name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Everyday at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Run the tests
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Login to Stackoverflow
        env:
          STACKOVERFLOW_EMAIL: ${{ secrets.STACKOVERFLOW_EMAIL }}
          STACKOVERFLOW_PASSWORD: ${{ secrets.STACKOVERFLOW_PASSWORD }}
        run: |
          python -m src.login
